name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      uses: actions/setup-cpp@v1
      with:
        cpp-version: '17'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make g++ libgtest-dev

    - name: Run tests
      run: make test